apiVersion: apps/v1
kind: Deployment
metadata:
  name: team4-accounts-deployment
  namespace: group1-team4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team4-accounts
  template:
    metadata:
      labels:
        app: team4-accounts
    spec:
      containers:
      - name: team4-accounts-container
        image: k8s-vga-worker1:5000/group1-team4-accounts:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9206
---
apiVersion: v1
kind: Service
metadata:
  name: team4-accounts-service
  namespace: group1-team4
spec:
  selector:
    app: team4-accounts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9206
      nodePort: 30411
  type: NodePort
