server:
  port: 9202

spring:
  profiles:
    active: "prod"
  application:
    name: "gatewayserver"
  cloud:
    gateway:
      discovery:
        locator:
          ## locate all services registered in Eureka server (Actuator to get the list of services)
          enabled: false
          lower-case-service-id: true
      httpclient:
        ## default 30000,
        connect-timeout: 1000
        ## default unlimited
        response-timeout: 2s
  security:
   oauth2:
    resourceserver:
     jwt:
      jwt-set-uri: "http://192.168.100.221:30490/realms/master/protocol/openid-connect/certs"

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"