spring:
  config:
    import: "optional:configserver:http://team4-configserver-service:80/"
  rabbitmq:
    host: rabbitmq.group1-team4
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          jwt-set-uri: "http://192.168.100.221:30490/realms/team4/protocol/openid-connect/certs"

eureka:
  client:
    serviceUrl:
      defaultZone: http://team4-eurekaserver-service:80/eureka/
