spring:
  config:
    import: "optional:configserver:http://team4-configserver-service:80/"
  rabbitmq:
    host: rabbitmq.group1-team4
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://team4-eurekaserver-service:80/eureka/
