pipeline {
    agent any
    environment {
        REGISTRY = "k8s-vga-worker1:5000"
        IMAGE_NAME = "group1-team4-cards"
        IMAGE_TAG = "latest"
        NAMESPACE = "group1-team4"
        JAVA_HOME = "/usr/local/java21"
        PATH = "${JAVA_HOME}/bin:${PATH}"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/msa-Team4/msa-edu.git'
            }
        }

        stage('Check Java Version') {
            steps {
                dir('cards') {
                    sh 'echo "Using Java from: $JAVA_HOME"'
                    sh 'java -version'
                }
            }
        }

        stage('Build with Maven') {
            steps {
                dir('cards') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Set Version from POM') {
            steps {
                dir('cards') {
                    script {
                        env.VERSION = sh(script: 'mvn help:evaluate -Dexpression=project.version -q -DforceStdout', returnStdout: true).trim()
                        echo "Set version from POM: ${VERSION}"
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('cards') {
                    sh "docker build -t ${REGISTRY}/${IMAGE_NAME}:v${VERSION} ."
                }
            }
        }
       
        stage('Push Docker Image') {
            steps {
                sh "docker push ${REGISTRY}/${IMAGE_NAME}:v${VERSION}"
            }
        }


        stage('Deploy and Service to Kubernetes') {
            steps {
                dir('cards') {
                    sh "kubectl apply -f ./cards.yaml -n ${NAMESPACE}"
                }
            }
        }

        stage('Deployment Image to Update') {
            steps {
                sh "kubectl set image deployment/team4-cards-deployment team4-cards-container=${REGISTRY}/${IMAGE_NAME}:v${VERSION} --namespace=${NAMESPACE}"
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}

