pipeline {
    agent any
    environment {
        REGISTRY = "k8s-vga-worker1:5000"
        IMAGE_NAME = "group1-team4-loans"
        IMAGE_TAG = "latest"
        NAMESPACE = "group1-team4"
        JAVA_HOME = "/usr/local/java21"
        PATH = "${JAVA_HOME}/bin:${PATH}"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/msa-Team4/msa-edu.git'
            }
        }

        stage('Check Java Version') {
            steps {
                dir('loans') {
                    sh 'echo "Using Java from: $JAVA_HOME"'
                    sh 'java -version'
                }
            }
        }

        stage('Build with Maven') {
            steps {
                dir('loans') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('loans') {
                    sh "docker build -t ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
            }
        }

        stage('Deploy and Service to Kubernetes') {
            steps {
                dir('loans') {
                    sh "kubectl apply -f ./app-loans.yaml -n ${NAMESPACE}"
                }
            }
        }

        stage('Deployment Image to Update') {
            steps {
                sh "kubectl set image deployment/team4-loans-deployment team4-loans-container=${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} --namespace=${NAMESPACE}"
            }
        }
    }
}

