apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      imagePullSecrets:
          - name: regcred
      containers:
        - name: postgres
          image: docker.io/library/postgres:15
          env:
            - name: POSTGRES_DB
              value: "keycloak"
            - name: POSTGRES_USER
              value: "keycloak"
            - name: POSTGRES_PASSWORD
              value: "keycloakpass"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: "/var/lib/postgresql/data"

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
      nodeSelector:
        kubernetes.io/hostname: k8s-vga-worker1
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
    - port: 5432
  selector:
    app: postgres