spring:
  config:
    import: "optional:configserver:http://192.168.100.221:30416/"
    # import: "optional:configserver:http://localhost:9200/"

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.100.221:30414/eureka/