server:
  port: 9200

spring:
  application:
    name: "configserver"
  profiles:
    active: git, prod
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/msa-Team4/msa-edu.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    bus-refresh:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
