apiVersion: apps/v1
kind: Deployment
metadata:
  name: team4-account-deployment
  namespace: group1-team4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team4-account

  template:
    metadata:
      labels:
        app: team4-account
    spec:
      containers:
      - name: team4-account-container
        image: k8s-vga-worker1:5000/group1-team4-accounts
        imagePullPolicy: Always
        ports:
        - containerPort: 9206
---
apiVersion: v1
kind: Service
metadata:
  name: team4-account-service
  namespace: group1-team4
spec:
  selector:
    app: team4-account
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9206
      nodePort: 30411
  type: NodePort

