# env:
#  - name: JAVA_HOME
#    value: "/usr/local/java21"
#  - name: PATH
#    value: "${JAVA_HOME}/bin:${env.PATH}"
global:
  namespace: group1-team4
  configMapName: team4-configmap
  activeProfile: prod
  # eurekaServerURL: "team4-eureka-sv:80"
  # configServerURL: "team4-cfg-sv:80"
  # gatewayServerURL: "team4-gw-sv:80"
  # accountsURL: "team4-account-sv:80"
  # cardsURL: "team4-card-sv:80"
  # loansURL: "team4-loan-sv:80"
  privateReposityroURL: k8s-vga-worker1:5000


accounts:
  enabled: false
cards:
  enabled: false
loans:
  enabled: false