pipeline {
    agent any
    environment {
        REGISTRY = "k8s-vga-worker1:5000"
        IMAGE_NAME = "demo-app-team4"
        IMAGE_TAG = "latest"
        NAMESPACE = "group1-team4"
        JAVA_HOME = "/usr/local/java21"
        PATH = "${JAVA_HOME}/bin:${PATH}"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/msa-Team4/msa-edu.git'
            }
        }
        stage('Build & Deploy') {
            steps {
                dir('springboot-edu') {
                    stage('Check Java Version') {
                        sh 'echo "Using Java from: $JAVA_HOME"'
                        sh 'java -version'
                    }

                    stage('Build with Maven') {
                        sh 'mvn clean package -DskipTests'
                    }

                    stage('Build Docker Image') {
                        sh "docker build -t ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} ."
                    }

                    stage('Push Docker Image') {
                        sh "docker push ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
                    }

                    stage('Deploy to Kubernetes') {
                        sh "kubectl apply -f ./demo-app.yaml -n ${NAMESPACE}"
                    }

                    stage('Update Deployment Image') {
                        sh "kubectl set image deployment/springboot-team4-deployment springboot-team4-container=${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} --namespace=${NAMESPACE}"
                    }
                }
            }
        }
    }
}
