apiVersion: apps/v1
kind: Deployment
metadata:
  name: team4-eurekaserver-deployment
  namespace: group1-team4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team4-eurekaserver
  template:
    metadata:
      labels:
        app: team4-eurekaserver
    spec:
      containers:
      - name: team4-eurekaserver-container
        image: k8s-vga-worker1:5000/group1-team4-eurekaserver:v0.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9201
---
apiVersion: v1
kind: Service
metadata:
  name: team4-eurekaserver-service
  namespace: group1-team4
spec:
  selector:
    app: team4-eurekaserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9201
      nodePort: 30414
  type: NodePort
