pipeline {
    agent any
    environment {
        REGISTRY = "k8s-vga-worker1:5000"
        IMAGE_NAME = "group1-team4-eurekaserver"
        IMAGE_TAG = "latest"
        NAME = "team4-eurekaserver"
        NAMESPACE = "group1-team4"
        JAVA_HOME = "/usr/local/java21"
        PATH = "${JAVA_HOME}/bin:${PATH}"
    }
    parameters {
        string(name: 'BRANCH', defaultValue: 'main', description: 'select branch to build')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "${params.BRANCH}", url: 'https://github.com/msa-Team4/msa-edu.git'                
            }
        }

        stage('Build with Maven') {
            steps {
                dir('eurekaserver') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
       
        stage('Build Docker Image') {
            steps {
                dir('eurekaserver') {
                    sh "docker build -t ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
            }
        }
        
        stage('Deploy and Service to Kubernetes') {
            steps {
                dir('eurekaserver') {
                    sh "kubectl apply -f ./eurekaserver.yaml -n ${NAMESPACE}"
                }
            }
        }

        stage('Deployment Image to Update') {
            steps {
                sh "kubectl set image deployment/${NAME}-deployment ${NAME}-container=${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} --namespace=${NAMESPACE}"

            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}

