# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: team4-gw-pod
containerName: gw-contain
serviceName: team4-gw-sv
appLabel: gw-lbl

replicaCount: 1

image:
  repository: group1-team4-gw


service:
  nodePort: 30634
