# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: team4-eureka-pod
containerName: eureka-contain
serviceName: team4-eureka-sv
appLabel: eureka-lbl

replicaCount: 1

image:
  repository: group1-team4-eureka-server


service:
  nodePort: 30635
