# ----------------------------------------------
# Kafka 내부 통신용 Headless Service
# ----------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: group1-team4  
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: internal
  clusterIP: None
  selector:
    app: kafka
---
# ----------------------------------------------
# Kafka 외부 접근용 LoadBalancer Service
# ----------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: group1-team4  
  labels:
    app: kafka
spec:
  type: LoadBalancer
  ports:
  - port: 9094
    targetPort: 9094
    protocol: TCP
    name: external
    nodePort: 30494
  selector:
    app: kafka
---
# ----------------------------------------------
# Kafka StatefulSet (내부 및 외부 Listener 구성)
# ----------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: group1-team4  
  labels:
    app: kafka
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        #bitnami/kafka:latest
        image: k8s-vga-worker1:5000/kafka:latest
        ports:
        - containerPort: 9092
          name: internal
        - containerPort: 9094
          name: external
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        # Kafka가 두 Listener를 사용하도록 설정 (내부: 9092, 외부: 9094)
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094"
        # 내부는 headless service를, 외부는 각 노드의 hostIP를 통해 접근하도록 구성
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-headless:9092,EXTERNAL://192.168.100.221:30494"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        # 외부 접근용 IP를 노드의 hostIP로 자동 할당 (환경에 따라 변경 필요)
        - name: EXTERNAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIPapiVersion: v1
---
kind: Service
metadata:
  name: zookeeper-service
  namespace: group1-team4
spec:
  selector:
    app: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: 2181

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  namespace: group1-team4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          #bitnami/zookeeper:latest
          image: k8s-vga-worker1:5000/zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          volumeMounts:
            - name: zk-data
              mountPath: /var/lib/zookeeper/data
            - name: zk-logs
              mountPath: /var/lib/zookeeper/logs
      volumes:
        - name: zk-data
          emptyDir: {}
        - name: zk-logs
          emptyDir: {}
