# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: team4-cfg-pod
containerName: cfg-contain
serviceName: team4-cfg-sv
appLabel: cfg-lbl

replicaCount: 1

image:
  repository: group1-team4-cfg


service:
  nodePort: 30633
